### ISSUE TITLE
[FEATURE REQUEST] Ability to update an order to "active" state.

### ISSUE THREAD

**Issue by rndfm** [rentle/rentle-api-feedback#3]
My rental store needs to be a self-service rental store where the customer books equipment online and collects the equiptment by themselves. There will be some sort of verification of the customer in place(pin code lock, camera ID verification) and then the order(booking) should be updated to be "active".

**Describe the solution you'd like**
A way to update the order to "active" through the API

**Comment by tooga** [comment]
Hi @rndfm, thanks for submitting the request! I think updating the order state via the API is a valid use case. I will add this to our backlog for consideration.
