### ISSUE TITLE
[HELP WANTED] How to get 200 status, only get 403

### ISSUE THREAD

**Issue by pablo-ferro** [rentle/rentle-api-feedback#5]
**What is the issue you are experiencing?**
I am constantly getting Forbidden 403 error despite the user and passwords I am introducing are correct.

**How have you tried to resolve the issue?**
I have deleted multiple times and created again a new API key but the issue remains. At the beginning I only gave read access to Orders as it is the part I am interested but at the end after giving access to everything the issue was still there.

**Additional context**

Also, your Contact Support button under Got a problem? section in my own shop does not work, the button is not linked.
Some basic example to GET data would be much appreciated to understand where to locate in the code the user and password as I feel that part is missing and probably what I am struggling with.

**Comment by pablo-ferro** [comment]
After some hours I placed the keys in the right place. Thank you

**Comment by juiceo** [comment]
Good to hear you were able to resolve the issue @pablo-ferro! 

Do you feel like we could improve the docs in some way to help others avoid running into the same thing in the future?

**Comment by juiceo** [comment]
> Some basic example to GET data would be much appreciated to understand where to locate in the code the user and password as I feel that part is missing and probably what I am struggling with.

@tooga We could add something like this to the docs, or perhaps create an `examples` folder in this repo with a simple example

**Comment by tooga** [comment]
Good idea, we could try to add e.g. a simple Node example to the docs that would also show how the request headers should be placed

**Comment by pablo-ferro** [comment]
Moi!

Thanks a lot for quick response. I am not proficient at all in API coding
but yesterday with python I ended up making work with this structure:

response = requests.get(url, headers=headers, auth=(username, password))

I know is quite simple logic but I was unsure where to place the keys and
the version.

My next steps are formatting the json output as it is quite nested.

Thanks,
Pablo

**Comment by juiceo** [comment]
Got it - we added now some more details to the API key creation flow in Admin regarding how to use the API key ID / secret to authenticate requests, hopefully that helps 👍  By the way, the relevant section in the docs, in case you missed it: https://api.rentle.io/admin/#tag/Authentication

I'll close this issue for now!

**Comment by pablo-ferro** [comment]
Thanks a lot!
